# SPDX-License-Identifier: MPL-2.0
import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

SCRIPT = Path(__file__).resolve().parents[1] / "check_license.py"
SPEC = importlib.util.spec_from_file_location("check_license", SCRIPT)
checker = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(checker)
LICENSE_TEXT = (SCRIPT.parents[1] / "LICENSE").read_text(encoding="utf-8")


class LicenseChecks(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory(prefix="kagitaba-license-test-")
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        self.git("init", "-q")
        self.write("LICENSE", LICENSE_TEXT)
        self.write("Cargo.toml", '# SPDX-License-Identifier: MPL-2.0\n[package]\nlicense = "MPL-2.0"\n')

    def git(self, *args):
        return subprocess.run(["git", "-C", str(self.root), *args], check=True, capture_output=True)

    def write(self, name, content):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def errors(self):
        return checker.check_repository(self.root)[1]

    def cli_root(self):
        """Build a temporary repository with a runnable copy of the CLI."""
        scripts = self.root / "scripts"
        scripts.mkdir(exist_ok=True)
        cli = scripts / "check_license.py"
        shutil.copy2(SCRIPT, cli)
        return cli

    def run_cli(self, cli, *, env=None):
        return subprocess.run(
            [sys.executable, "-B", str(cli)],
            text=True,
            capture_output=True,
            env=env,
            check=False,
        )

    def test_all_supported_formats_and_shebangs_pass(self):
        fixtures = {
            "file.rs": "// SPDX-License-Identifier: MPL-2.0\n",
            "file.py": "# SPDX-License-Identifier: MPL-2.0\n",
            "file.sh": "# SPDX-License-Identifier: MPL-2.0\n",
            "file.toml": "# SPDX-License-Identifier: MPL-2.0\n",
            "file.yml": "# SPDX-License-Identifier: MPL-2.0\n",
            "file.yaml": "# SPDX-License-Identifier: MPL-2.0\n",
            "file.md": "<!-- SPDX-License-Identifier: MPL-2.0 -->\n",
            "file.txt": "SPDX-License-Identifier: MPL-2.0\n",
        }
        for name, content in fixtures.items():
            self.write(name, content)
        self.write(".gitignore", "# SPDX-License-Identifier: MPL-2.0\n")
        self.write("Cargo.lock", "# SPDX-License-Identifier: MPL-2.0\n# Generated by Cargo\n")
        self.write("script.sh", "#!/bin/sh\n# SPDX-License-Identifier: MPL-2.0\nexit 0\n")
        self.assertEqual(self.errors(), [])

    def test_missing_wrong_and_misplaced_headers_fail(self):
        for content in [
            "fn main() {}\n",
            "// SPDX-License-Identifier: MIT\n",
            "\n// SPDX-License-Identifier: MPL-2.0\n",
            "// SPDX-License-Identifier: MPL-2.0 OR MIT\n",
            "SPDX-License-Identifier: MPL-2.0\n",
        ]:
            with self.subTest(content=content):
                self.write("file.rs", content)
                self.assertIsNotNone(checker.check_header(self.root, "file.rs"))

    def test_header_after_shebang_must_be_immediate(self):
        self.write("script.py", "#!/usr/bin/env python3\n\n# SPDX-License-Identifier: MPL-2.0\n")
        self.assertIsNotNone(checker.check_header(self.root, "script.py"))

    def test_oversized_shebang_cannot_hide_a_header_on_the_same_line(self):
        for suffix in [".py", ".sh"]:
            with self.subTest(suffix=suffix):
                name = f"script{suffix}"
                (self.root / name).write_bytes(b"#!" + b"x" * 4094 + b"# SPDX-License-Identifier: MPL-2.0\n")
                self.assertIsNotNone(checker.check_header(self.root, name))

    def test_tracked_and_new_files_are_checked(self):
        self.write("tracked.rs", "fn main() {}\n")
        self.git("add", "tracked.rs")
        self.write("new.rs", "fn main() {}\n")
        errors = self.errors()
        self.assertTrue(any("tracked.rs" in error for error in errors))
        self.assertTrue(any("new.rs" in error for error in errors))

    def test_ignored_artifacts_are_excluded_but_tracked_files_are_not(self):
        self.write(".gitignore", "# SPDX-License-Identifier: MPL-2.0\ntarget/\n")
        self.write("target/ignored.txt", "build artifact\n")
        self.assertEqual(self.errors(), [])
        self.git("add", "-f", "target/ignored.txt")
        self.assertTrue(any("target/ignored.txt" in error for error in self.errors()))

    def test_unknown_format_is_not_silently_skipped(self):
        (self.root / "image.png").write_bytes(b"\x89PNG\r\n")
        self.assertTrue(any("unsupported file format" in error for error in self.errors()))

    def test_symlink_is_rejected_without_reading_target(self):
        (self.root / "linked.rs").symlink_to(self.root / "does-not-exist")
        self.assertTrue(any("symlink" in error for error in self.errors()))

    def test_tracked_file_under_symlinked_directory_is_rejected(self):
        self.write("src/file.rs", "// SPDX-License-Identifier: MPL-2.0\n")
        self.git("add", "src/file.rs")
        (self.root / "src/file.rs").unlink()
        (self.root / "src").rmdir()
        with tempfile.TemporaryDirectory(prefix="kagitaba-license-target-") as target:
            outside = Path(target)
            (outside / "file.rs").write_text("// SPDX-License-Identifier: MPL-2.0\n")
            (self.root / "src").symlink_to(outside, target_is_directory=True)
            self.assertTrue(any("src/file.rs" in error for error in self.errors()))

    def test_missing_indexed_file_and_empty_file_fail(self):
        self.write("file.rs", "// SPDX-License-Identifier: MPL-2.0\n")
        self.git("add", "file.rs")
        (self.root / "file.rs").unlink()
        self.write("empty.rs", "")
        errors = self.errors()
        self.assertTrue(any("file.rs" in error for error in errors))
        self.assertTrue(any("empty.rs" in error for error in errors))

    def test_non_utf8_header_fails(self):
        (self.root / "file.rs").write_bytes(b"\xff\n")
        self.assertTrue(any("UTF-8" in error for error in self.errors()))

    def test_filename_newlines_are_escaped_in_diagnostics(self):
        self.write("bad\nname.rs", "missing header\n")
        errors = self.errors()
        self.assertTrue(any("bad\\nname.rs" in error for error in errors))
        self.assertTrue(all("\n" not in error for error in errors))

    def test_missing_and_wrong_manifest_license_fail(self):
        for declaration in ["", 'license = "MIT"\n']:
            with self.subTest(declaration=declaration):
                self.write("Cargo.toml", "# SPDX-License-Identifier: MPL-2.0\n[package]\n" + declaration)
                self.assertTrue(any("package.license" in error for error in self.errors()))

    def test_malformed_or_non_table_package_metadata_fails(self):
        for body in ["package = 1\n", 'package = ["invalid"]\n', "[package]\nlicense =\n"]:
            with self.subTest(body=body):
                self.write("Cargo.toml", "# SPDX-License-Identifier: MPL-2.0\n" + body)
                self.assertTrue(any("Cargo.toml:" in error for error in self.errors()))

    def test_license_body_changes_fail_but_whitespace_changes_pass(self):
        self.write("LICENSE", LICENSE_TEXT.replace("Mozilla Public License Version 2.0", "Different License"))
        self.assertTrue(any("verified copy" in error for error in self.errors()))
        self.write("LICENSE", LICENSE_TEXT.replace("\n\n", "\n\n\n"))
        self.assertEqual(self.errors(), [])

    def test_main_cli_success_reports_stdout_and_exit_code(self):
        cli = self.cli_root()

        result = self.run_cli(cli)

        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stderr, "")
        self.assertEqual(
            result.stdout,
            "PASS: 3 files have MPL-2.0 SPDX headers; Cargo metadata and LICENSE agree\n",
        )

    def test_main_cli_check_failure_reports_stderr_and_exit_code(self):
        cli = self.cli_root()
        self.write("broken.rs", "fn main() {}\n")

        result = self.run_cli(cli)

        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, "")
        self.assertIn("ERROR: 'broken.rs':", result.stderr)
        self.assertIn("first line must be", result.stderr)

    def test_main_cli_git_enumeration_failure_reports_stderr_and_exit_code(self):
        cli = self.cli_root()
        fake_bin = self.root / "fake-bin"
        fake_bin.mkdir()
        fake_git = fake_bin / "git"
        fake_git.write_text("#!/bin/sh\nexit 23\n", encoding="utf-8")
        fake_git.chmod(0o755)
        env = os.environ.copy()
        env["PATH"] = str(fake_bin)

        result = self.run_cli(cli, env=env)

        self.assertEqual(result.returncode, 1)
        self.assertEqual(result.stdout, "")
        self.assertEqual(result.stderr, "ERROR: cannot enumerate repository files with git\n")

    def test_missing_cargo_manifest_and_license_are_reported(self):
        manifest = self.root / "Cargo.toml"
        license_file = self.root / "LICENSE"
        manifest.unlink()
        license_file.unlink()

        self.assertEqual(
            checker.check_metadata(self.root),
            [
                "Cargo.toml: a regular manifest file is required",
                "LICENSE: a regular license file is required",
            ],
        )

    def test_license_decode_failure_is_reported(self):
        (self.root / "LICENSE").write_bytes(b"SPDX-License-Identifier: MPL-2.0\n\xff\n")

        self.assertEqual(checker.check_metadata(self.root), ["LICENSE: cannot read license text"])

    def test_license_read_failure_is_reported_without_filesystem_permissions(self):
        license_file = self.root / "LICENSE"
        original_read_text = Path.read_text

        def fail_for_license(path, *args, **kwargs):
            if path == license_file:
                raise PermissionError("simulated unreadable license")
            return original_read_text(path, *args, **kwargs)

        with patch.object(Path, "read_text", fail_for_license):
            errors = checker.check_metadata(self.root)

        self.assertEqual(errors, ["LICENSE: cannot read license text"])


if __name__ == "__main__":
    unittest.main()
